### ISSUE TITLE
Nice library, just curious of the status?

### ISSUE THREAD

**Issue by mikeaustin** [bkazi/react-layout-transition#8]
Like anyone looking for a library, I look at popularity and stability. I came across react-layout-transition after looking for a cross-platform Native/Web animation library. I love to try new things out, but when using something for larger project one has to dig a bit deeper.

BTW, what are your thoughts on animatedjs/animated and bringking/react-web-animation?

**Comment by bkazi** [comment]
Thanks
I'm willing to work on the library and fix bugs/add features if possible (all help would be appreciated as well)
Also working on some more complex demos to better showcase capabilities and test stability
But the library I still pre-production and I'd recommend you toy around with it and see if it works for your use case before committing to using it since right now since it was built to fit what I needed at the time
I'd love to generalise it to be useful to more people if I could
